// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demoProtoc.proto

package com.senpure.io.protoc;

public final class DemoMessage {
  private DemoMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AuthorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // required int32 phone = 2;
    boolean hasPhone();
    int getPhone();
  }
  public static final class Author extends
      com.google.protobuf.GeneratedMessage
      implements AuthorOrBuilder {
    // Use Author.newBuilder() to construct.
    private Author(Builder builder) {
      super(builder);
    }
    private Author(boolean noInit) {}
    
    private static final Author defaultInstance;
    public static Author getDefaultInstance() {
      return defaultInstance;
    }
    
    public Author getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DemoMessage.internal_static_Author_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DemoMessage.internal_static_Author_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 phone = 2;
    public static final int PHONE_FIELD_NUMBER = 2;
    private int phone_;
    public boolean hasPhone() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getPhone() {
      return phone_;
    }
    
    private void initFields() {
      name_ = "";
      phone_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPhone()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, phone_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, phone_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Author parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Author parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Author parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Author parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Author parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Author parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Author parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Author parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Author parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Author parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Author prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements AuthorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DemoMessage.internal_static_Author_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DemoMessage.internal_static_Author_fieldAccessorTable;
      }
      
      // Construct using com.senpure.io.protoc.DemoMessage.Author.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        phone_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Author.getDescriptor();
      }
      
      public Author getDefaultInstanceForType() {
        return Author.getDefaultInstance();
      }
      
      public Author build() {
        Author result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Author buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Author result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Author buildPartial() {
        Author result = new Author(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.phone_ = phone_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Author) {
          return mergeFrom((Author)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Author other) {
        if (other == Author.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasPhone()) {
          setPhone(other.getPhone());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasPhone()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              phone_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // required int32 phone = 2;
      private int phone_ ;
      public boolean hasPhone() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getPhone() {
        return phone_;
      }
      public Builder setPhone(int value) {
        bitField0_ |= 0x00000002;
        phone_ = value;
        onChanged();
        return this;
      }
      public Builder clearPhone() {
        bitField0_ = (bitField0_ & ~0x00000002);
        phone_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Author)
    }
    
    static {
      defaultInstance = new Author(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Author)
  }
  
  public interface BookOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // required int32 price = 2;
    boolean hasPrice();
    int getPrice();
    
    // required .Author author = 3;
    boolean hasAuthor();
    Author getAuthor();
    AuthorOrBuilder getAuthorOrBuilder();
  }
  public static final class Book extends
      com.google.protobuf.GeneratedMessage
      implements BookOrBuilder {
    // Use Book.newBuilder() to construct.
    private Book(Builder builder) {
      super(builder);
    }
    private Book(boolean noInit) {}
    
    private static final Book defaultInstance;
    public static Book getDefaultInstance() {
      return defaultInstance;
    }
    
    public Book getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DemoMessage.internal_static_Book_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DemoMessage.internal_static_Book_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 price = 2;
    public static final int PRICE_FIELD_NUMBER = 2;
    private int price_;
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getPrice() {
      return price_;
    }
    
    // required .Author author = 3;
    public static final int AUTHOR_FIELD_NUMBER = 3;
    private Author author_;
    public boolean hasAuthor() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public Author getAuthor() {
      return author_;
    }
    public AuthorOrBuilder getAuthorOrBuilder() {
      return author_;
    }
    
    private void initFields() {
      name_ = "";
      price_ = 0;
      author_ = Author.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAuthor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getAuthor().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, price_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, author_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, price_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, author_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Book parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Book parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Book parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Book parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Book parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Book parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Book parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Book parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Book parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Book parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Book prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements BookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DemoMessage.internal_static_Book_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DemoMessage.internal_static_Book_fieldAccessorTable;
      }
      
      // Construct using com.senpure.io.protoc.DemoMessage.Book.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAuthorFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        price_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (authorBuilder_ == null) {
          author_ = Author.getDefaultInstance();
        } else {
          authorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Book.getDescriptor();
      }
      
      public Book getDefaultInstanceForType() {
        return Book.getDefaultInstance();
      }
      
      public Book build() {
        Book result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Book buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Book result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Book buildPartial() {
        Book result = new Book(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.price_ = price_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (authorBuilder_ == null) {
          result.author_ = author_;
        } else {
          result.author_ = authorBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Book) {
          return mergeFrom((Book)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Book other) {
        if (other == Book.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasAuthor()) {
          mergeAuthor(other.getAuthor());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasPrice()) {
          
          return false;
        }
        if (!hasAuthor()) {
          
          return false;
        }
        if (!getAuthor().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              price_ = input.readInt32();
              break;
            }
            case 26: {
              Author.Builder subBuilder = Author.newBuilder();
              if (hasAuthor()) {
                subBuilder.mergeFrom(getAuthor());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setAuthor(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // required int32 price = 2;
      private int price_ ;
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getPrice() {
        return price_;
      }
      public Builder setPrice(int value) {
        bitField0_ |= 0x00000002;
        price_ = value;
        onChanged();
        return this;
      }
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000002);
        price_ = 0;
        onChanged();
        return this;
      }
      
      // required .Author author = 3;
      private Author author_ = Author.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Author, Author.Builder, AuthorOrBuilder> authorBuilder_;
      public boolean hasAuthor() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public Author getAuthor() {
        if (authorBuilder_ == null) {
          return author_;
        } else {
          return authorBuilder_.getMessage();
        }
      }
      public Builder setAuthor(Author value) {
        if (authorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          author_ = value;
          onChanged();
        } else {
          authorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setAuthor(
          Author.Builder builderForValue) {
        if (authorBuilder_ == null) {
          author_ = builderForValue.build();
          onChanged();
        } else {
          authorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeAuthor(Author value) {
        if (authorBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              author_ != Author.getDefaultInstance()) {
            author_ =
              Author.newBuilder(author_).mergeFrom(value).buildPartial();
          } else {
            author_ = value;
          }
          onChanged();
        } else {
          authorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearAuthor() {
        if (authorBuilder_ == null) {
          author_ = Author.getDefaultInstance();
          onChanged();
        } else {
          authorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public Author.Builder getAuthorBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getAuthorFieldBuilder().getBuilder();
      }
      public AuthorOrBuilder getAuthorOrBuilder() {
        if (authorBuilder_ != null) {
          return authorBuilder_.getMessageOrBuilder();
        } else {
          return author_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          Author, Author.Builder, AuthorOrBuilder>
          getAuthorFieldBuilder() {
        if (authorBuilder_ == null) {
          authorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Author, Author.Builder, AuthorOrBuilder>(
                  author_,
                  getParentForChildren(),
                  isClean());
          author_ = null;
        }
        return authorBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:Book)
    }
    
    static {
      defaultInstance = new Book(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Book)
  }
  
  public interface StudentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // required int32 age = 2;
    boolean hasAge();
    int getAge();
    
    // required int32 num = 3;
    boolean hasNum();
    int getNum();
    
    // repeated int32 luckNums = 4;
    java.util.List<Integer> getLuckNumsList();
    int getLuckNumsCount();
    int getLuckNums(int index);
    
    // repeated string provide = 5;
    java.util.List<String> getProvideList();
    int getProvideCount();
    String getProvide(int index);
    
    // required .Book readBook = 6;
    boolean hasReadBook();
    Book getReadBook();
    BookOrBuilder getReadBookOrBuilder();
    
    // repeated .Book likeBooks = 7;
    java.util.List<Book>
        getLikeBooksList();
    Book getLikeBooks(int index);
    int getLikeBooksCount();
    java.util.List<? extends BookOrBuilder>
        getLikeBooksOrBuilderList();
    BookOrBuilder getLikeBooksOrBuilder(
            int index);
  }
  public static final class Student extends
      com.google.protobuf.GeneratedMessage
      implements StudentOrBuilder {
    // Use Student.newBuilder() to construct.
    private Student(Builder builder) {
      super(builder);
    }
    private Student(boolean noInit) {}
    
    private static final Student defaultInstance;
    public static Student getDefaultInstance() {
      return defaultInstance;
    }
    
    public Student getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DemoMessage.internal_static_Student_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DemoMessage.internal_static_Student_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 age = 2;
    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    public boolean hasAge() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getAge() {
      return age_;
    }
    
    // required int32 num = 3;
    public static final int NUM_FIELD_NUMBER = 3;
    private int num_;
    public boolean hasNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getNum() {
      return num_;
    }
    
    // repeated int32 luckNums = 4;
    public static final int LUCKNUMS_FIELD_NUMBER = 4;
    private java.util.List<Integer> luckNums_;
    public java.util.List<Integer>
        getLuckNumsList() {
      return luckNums_;
    }
    public int getLuckNumsCount() {
      return luckNums_.size();
    }
    public int getLuckNums(int index) {
      return luckNums_.get(index);
    }
    
    // repeated string provide = 5;
    public static final int PROVIDE_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList provide_;
    public java.util.List<String>
        getProvideList() {
      return provide_;
    }
    public int getProvideCount() {
      return provide_.size();
    }
    public String getProvide(int index) {
      return provide_.get(index);
    }
    
    // required .Book readBook = 6;
    public static final int READBOOK_FIELD_NUMBER = 6;
    private Book readBook_;
    public boolean hasReadBook() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public Book getReadBook() {
      return readBook_;
    }
    public BookOrBuilder getReadBookOrBuilder() {
      return readBook_;
    }
    
    // repeated .Book likeBooks = 7;
    public static final int LIKEBOOKS_FIELD_NUMBER = 7;
    private java.util.List<Book> likeBooks_;
    public java.util.List<Book> getLikeBooksList() {
      return likeBooks_;
    }
    public java.util.List<? extends BookOrBuilder>
        getLikeBooksOrBuilderList() {
      return likeBooks_;
    }
    public int getLikeBooksCount() {
      return likeBooks_.size();
    }
    public Book getLikeBooks(int index) {
      return likeBooks_.get(index);
    }
    public BookOrBuilder getLikeBooksOrBuilder(
        int index) {
      return likeBooks_.get(index);
    }
    
    private void initFields() {
      name_ = "";
      age_ = 0;
      num_ = 0;
      luckNums_ = java.util.Collections.emptyList();;
      provide_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      readBook_ = Book.getDefaultInstance();
      likeBooks_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAge()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReadBook()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getReadBook().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getLikeBooksCount(); i++) {
        if (!getLikeBooks(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, age_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, num_);
      }
      for (int i = 0; i < luckNums_.size(); i++) {
        output.writeInt32(4, luckNums_.get(i));
      }
      for (int i = 0; i < provide_.size(); i++) {
        output.writeBytes(5, provide_.getByteString(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(6, readBook_);
      }
      for (int i = 0; i < likeBooks_.size(); i++) {
        output.writeMessage(7, likeBooks_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, num_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < luckNums_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(luckNums_.get(i));
        }
        size += dataSize;
        size += 1 * getLuckNumsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < provide_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(provide_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getProvideList().size();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, readBook_);
      }
      for (int i = 0; i < likeBooks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, likeBooks_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Student prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DemoMessage.internal_static_Student_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DemoMessage.internal_static_Student_fieldAccessorTable;
      }
      
      // Construct using com.senpure.io.protoc.DemoMessage.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getReadBookFieldBuilder();
          getLikeBooksFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        num_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        luckNums_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000008);
        provide_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (readBookBuilder_ == null) {
          readBook_ = Book.getDefaultInstance();
        } else {
          readBookBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        if (likeBooksBuilder_ == null) {
          likeBooks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          likeBooksBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Student.getDescriptor();
      }
      
      public Student getDefaultInstanceForType() {
        return Student.getDefaultInstance();
      }
      
      public Student build() {
        Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Student buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Student buildPartial() {
        Student result = new Student(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.age_ = age_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.num_ = num_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          luckNums_ = java.util.Collections.unmodifiableList(luckNums_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.luckNums_ = luckNums_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          provide_ = new com.google.protobuf.UnmodifiableLazyStringList(
              provide_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.provide_ = provide_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000008;
        }
        if (readBookBuilder_ == null) {
          result.readBook_ = readBook_;
        } else {
          result.readBook_ = readBookBuilder_.build();
        }
        if (likeBooksBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            likeBooks_ = java.util.Collections.unmodifiableList(likeBooks_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.likeBooks_ = likeBooks_;
        } else {
          result.likeBooks_ = likeBooksBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Student) {
          return mergeFrom((Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Student other) {
        if (other == Student.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (other.hasNum()) {
          setNum(other.getNum());
        }
        if (!other.luckNums_.isEmpty()) {
          if (luckNums_.isEmpty()) {
            luckNums_ = other.luckNums_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureLuckNumsIsMutable();
            luckNums_.addAll(other.luckNums_);
          }
          onChanged();
        }
        if (!other.provide_.isEmpty()) {
          if (provide_.isEmpty()) {
            provide_ = other.provide_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureProvideIsMutable();
            provide_.addAll(other.provide_);
          }
          onChanged();
        }
        if (other.hasReadBook()) {
          mergeReadBook(other.getReadBook());
        }
        if (likeBooksBuilder_ == null) {
          if (!other.likeBooks_.isEmpty()) {
            if (likeBooks_.isEmpty()) {
              likeBooks_ = other.likeBooks_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureLikeBooksIsMutable();
              likeBooks_.addAll(other.likeBooks_);
            }
            onChanged();
          }
        } else {
          if (!other.likeBooks_.isEmpty()) {
            if (likeBooksBuilder_.isEmpty()) {
              likeBooksBuilder_.dispose();
              likeBooksBuilder_ = null;
              likeBooks_ = other.likeBooks_;
              bitField0_ = (bitField0_ & ~0x00000040);
              likeBooksBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getLikeBooksFieldBuilder() : null;
            } else {
              likeBooksBuilder_.addAllMessages(other.likeBooks_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasAge()) {
          
          return false;
        }
        if (!hasNum()) {
          
          return false;
        }
        if (!hasReadBook()) {
          
          return false;
        }
        if (!getReadBook().isInitialized()) {
          
          return false;
        }
        for (int i = 0; i < getLikeBooksCount(); i++) {
          if (!getLikeBooks(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              age_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              num_ = input.readInt32();
              break;
            }
            case 32: {
              ensureLuckNumsIsMutable();
              luckNums_.add(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addLuckNums(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 42: {
              ensureProvideIsMutable();
              provide_.add(input.readBytes());
              break;
            }
            case 50: {
              Book.Builder subBuilder = Book.newBuilder();
              if (hasReadBook()) {
                subBuilder.mergeFrom(getReadBook());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setReadBook(subBuilder.buildPartial());
              break;
            }
            case 58: {
              Book.Builder subBuilder = Book.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addLikeBooks(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // required int32 age = 2;
      private int age_ ;
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getAge() {
        return age_;
      }
      public Builder setAge(int value) {
        bitField0_ |= 0x00000002;
        age_ = value;
        onChanged();
        return this;
      }
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 num = 3;
      private int num_ ;
      public boolean hasNum() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getNum() {
        return num_;
      }
      public Builder setNum(int value) {
        bitField0_ |= 0x00000004;
        num_ = value;
        onChanged();
        return this;
      }
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        num_ = 0;
        onChanged();
        return this;
      }
      
      // repeated int32 luckNums = 4;
      private java.util.List<Integer> luckNums_ = java.util.Collections.emptyList();;
      private void ensureLuckNumsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          luckNums_ = new java.util.ArrayList<Integer>(luckNums_);
          bitField0_ |= 0x00000008;
         }
      }
      public java.util.List<Integer>
          getLuckNumsList() {
        return java.util.Collections.unmodifiableList(luckNums_);
      }
      public int getLuckNumsCount() {
        return luckNums_.size();
      }
      public int getLuckNums(int index) {
        return luckNums_.get(index);
      }
      public Builder setLuckNums(
          int index, int value) {
        ensureLuckNumsIsMutable();
        luckNums_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addLuckNums(int value) {
        ensureLuckNumsIsMutable();
        luckNums_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllLuckNums(
          Iterable<? extends Integer> values) {
        ensureLuckNumsIsMutable();
        super.addAll(values, luckNums_);
        onChanged();
        return this;
      }
      public Builder clearLuckNums() {
        luckNums_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      
      // repeated string provide = 5;
      private com.google.protobuf.LazyStringList provide_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureProvideIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          provide_ = new com.google.protobuf.LazyStringArrayList(provide_);
          bitField0_ |= 0x00000010;
         }
      }
      public java.util.List<String>
          getProvideList() {
        return java.util.Collections.unmodifiableList(provide_);
      }
      public int getProvideCount() {
        return provide_.size();
      }
      public String getProvide(int index) {
        return provide_.get(index);
      }
      public Builder setProvide(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProvideIsMutable();
        provide_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addProvide(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProvideIsMutable();
        provide_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllProvide(
          Iterable<String> values) {
        ensureProvideIsMutable();
        super.addAll(values, provide_);
        onChanged();
        return this;
      }
      public Builder clearProvide() {
        provide_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      void addProvide(com.google.protobuf.ByteString value) {
        ensureProvideIsMutable();
        provide_.add(value);
        onChanged();
      }
      
      // required .Book readBook = 6;
      private Book readBook_ = Book.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Book, Book.Builder, BookOrBuilder> readBookBuilder_;
      public boolean hasReadBook() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public Book getReadBook() {
        if (readBookBuilder_ == null) {
          return readBook_;
        } else {
          return readBookBuilder_.getMessage();
        }
      }
      public Builder setReadBook(Book value) {
        if (readBookBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          readBook_ = value;
          onChanged();
        } else {
          readBookBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder setReadBook(
          Book.Builder builderForValue) {
        if (readBookBuilder_ == null) {
          readBook_ = builderForValue.build();
          onChanged();
        } else {
          readBookBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder mergeReadBook(Book value) {
        if (readBookBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              readBook_ != Book.getDefaultInstance()) {
            readBook_ =
              Book.newBuilder(readBook_).mergeFrom(value).buildPartial();
          } else {
            readBook_ = value;
          }
          onChanged();
        } else {
          readBookBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder clearReadBook() {
        if (readBookBuilder_ == null) {
          readBook_ = Book.getDefaultInstance();
          onChanged();
        } else {
          readBookBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      public Book.Builder getReadBookBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getReadBookFieldBuilder().getBuilder();
      }
      public BookOrBuilder getReadBookOrBuilder() {
        if (readBookBuilder_ != null) {
          return readBookBuilder_.getMessageOrBuilder();
        } else {
          return readBook_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          Book, Book.Builder, BookOrBuilder>
          getReadBookFieldBuilder() {
        if (readBookBuilder_ == null) {
          readBookBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Book, Book.Builder, BookOrBuilder>(
                  readBook_,
                  getParentForChildren(),
                  isClean());
          readBook_ = null;
        }
        return readBookBuilder_;
      }
      
      // repeated .Book likeBooks = 7;
      private java.util.List<Book> likeBooks_ =
        java.util.Collections.emptyList();
      private void ensureLikeBooksIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          likeBooks_ = new java.util.ArrayList<Book>(likeBooks_);
          bitField0_ |= 0x00000040;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          Book, Book.Builder, BookOrBuilder> likeBooksBuilder_;
      
      public java.util.List<Book> getLikeBooksList() {
        if (likeBooksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(likeBooks_);
        } else {
          return likeBooksBuilder_.getMessageList();
        }
      }
      public int getLikeBooksCount() {
        if (likeBooksBuilder_ == null) {
          return likeBooks_.size();
        } else {
          return likeBooksBuilder_.getCount();
        }
      }
      public Book getLikeBooks(int index) {
        if (likeBooksBuilder_ == null) {
          return likeBooks_.get(index);
        } else {
          return likeBooksBuilder_.getMessage(index);
        }
      }
      public Builder setLikeBooks(
          int index, Book value) {
        if (likeBooksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLikeBooksIsMutable();
          likeBooks_.set(index, value);
          onChanged();
        } else {
          likeBooksBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setLikeBooks(
          int index, Book.Builder builderForValue) {
        if (likeBooksBuilder_ == null) {
          ensureLikeBooksIsMutable();
          likeBooks_.set(index, builderForValue.build());
          onChanged();
        } else {
          likeBooksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addLikeBooks(Book value) {
        if (likeBooksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLikeBooksIsMutable();
          likeBooks_.add(value);
          onChanged();
        } else {
          likeBooksBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addLikeBooks(
          int index, Book value) {
        if (likeBooksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLikeBooksIsMutable();
          likeBooks_.add(index, value);
          onChanged();
        } else {
          likeBooksBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addLikeBooks(
          Book.Builder builderForValue) {
        if (likeBooksBuilder_ == null) {
          ensureLikeBooksIsMutable();
          likeBooks_.add(builderForValue.build());
          onChanged();
        } else {
          likeBooksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addLikeBooks(
          int index, Book.Builder builderForValue) {
        if (likeBooksBuilder_ == null) {
          ensureLikeBooksIsMutable();
          likeBooks_.add(index, builderForValue.build());
          onChanged();
        } else {
          likeBooksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllLikeBooks(
          Iterable<? extends Book> values) {
        if (likeBooksBuilder_ == null) {
          ensureLikeBooksIsMutable();
          super.addAll(values, likeBooks_);
          onChanged();
        } else {
          likeBooksBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearLikeBooks() {
        if (likeBooksBuilder_ == null) {
          likeBooks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          likeBooksBuilder_.clear();
        }
        return this;
      }
      public Builder removeLikeBooks(int index) {
        if (likeBooksBuilder_ == null) {
          ensureLikeBooksIsMutable();
          likeBooks_.remove(index);
          onChanged();
        } else {
          likeBooksBuilder_.remove(index);
        }
        return this;
      }
      public Book.Builder getLikeBooksBuilder(
          int index) {
        return getLikeBooksFieldBuilder().getBuilder(index);
      }
      public BookOrBuilder getLikeBooksOrBuilder(
          int index) {
        if (likeBooksBuilder_ == null) {
          return likeBooks_.get(index);  } else {
          return likeBooksBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends BookOrBuilder>
           getLikeBooksOrBuilderList() {
        if (likeBooksBuilder_ != null) {
          return likeBooksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(likeBooks_);
        }
      }
      public Book.Builder addLikeBooksBuilder() {
        return getLikeBooksFieldBuilder().addBuilder(
            Book.getDefaultInstance());
      }
      public Book.Builder addLikeBooksBuilder(
          int index) {
        return getLikeBooksFieldBuilder().addBuilder(
            index, Book.getDefaultInstance());
      }
      public java.util.List<Book.Builder>
           getLikeBooksBuilderList() {
        return getLikeBooksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Book, Book.Builder, BookOrBuilder>
          getLikeBooksFieldBuilder() {
        if (likeBooksBuilder_ == null) {
          likeBooksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Book, Book.Builder, BookOrBuilder>(
                  likeBooks_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          likeBooks_ = null;
        }
        return likeBooksBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:Student)
    }
    
    static {
      defaultInstance = new Student(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Student)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Author_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Author_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Book_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Book_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Student_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Student_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020demoProtoc.proto\"%\n\006Author\022\014\n\004name\030\001 \002" +
      "(\t\022\r\n\005phone\030\002 \002(\005\"<\n\004Book\022\014\n\004name\030\001 \002(\t\022" +
      "\r\n\005price\030\002 \002(\005\022\027\n\006author\030\003 \002(\0132\007.Author\"" +
      "\207\001\n\007Student\022\014\n\004name\030\001 \002(\t\022\013\n\003age\030\002 \002(\005\022\013" +
      "\n\003num\030\003 \002(\005\022\020\n\010luckNums\030\004 \003(\005\022\017\n\007provide" +
      "\030\005 \003(\t\022\027\n\010readBook\030\006 \002(\0132\005.Book\022\030\n\tlikeB" +
      "ooks\030\007 \003(\0132\005.BookB$\n\025com.senpure.io.prot" +
      "ocB\013DemoMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Author_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Author_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Author_descriptor,
              new String[] { "Name", "Phone", },
              Author.class,
              Author.Builder.class);
          internal_static_Book_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Book_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Book_descriptor,
              new String[] { "Name", "Price", "Author", },
              Book.class,
              Book.Builder.class);
          internal_static_Student_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Student_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Student_descriptor,
              new String[] { "Name", "Age", "Num", "LuckNums", "Provide", "ReadBook", "LikeBooks", },
              Student.class,
              Student.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
